[build]
  command = "npm run build"
  publish = "ufev-dashboard/build"
  functions = "netlify/functions"

[dev]
  command = "npm --prefix ufev-dashboard start"
  port = 8888
  targetPort = 3000
  functionsPort = 9999

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/fetch-metrics"
  status = 200
